#!/bin/sh

rm -f publications.bib
cat bibdefs.bib weirich.bib > publications.bib

bibtex2html -debug -m "bibdefs.bib" -d -r -nodoc -t "<a
href=http://www.cis.upenn.edu/~sweirich> Stephanie Weirich's</a>
Publications" --footer "<p> The documents
appearing on this page are included by the contributing authors as a
means to ensure timely dissemination of scholarly and technical work
on a non-commercial basis. Copyright and all rights therein are
maintained by the authors or by other copyright holders,
notwithstanding that they have offered their works here
electronically. It is understood that all persons copying this
information will adhere to the terms and constraints invoked by each
author's copyright. These works may not be reposted without the
explicit permission of the copyright holder." publications.bib


